# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: Inputs
    displayName: Enter first input
    type: string
    default: Helloworld

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo ${{parameters.Inputs}}