# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: firstinput
    displayName: Enter first input
    type: string
    default: Helloworld
  - name: secondinput
    displayName: Enter second input
    type: string
    default: Insane

steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

- script: |
    pwd
    ls -lrta
    chmod 755 newscript.sh
    /home/vsts/work/1/s/newscript.sh ${{parameters.firstinput}} ${{parameters.secondinput}}
    